"""Centralized visual constants shared across UI components."""

WINDOW_BACKGROUND = "#181818"
FRAME_BACKGROUND = "#242424"
TEXT_COLOR = "#ffffff"
ACCENT_COLOR = "#569e6a"
ACCENT_COLOR_HOVER = "#3e734c"
DISABLED_COLOR = "#6e6e6e"
DISABLED_COLOR_HOVER = "#4a4a4a"
SETTINGS_PANEL_FILL = "#1e1e1e"
SETTINGS_BORDER_COLOR = "#3a3a3a"
SETTINGS_MESSAGE_COLOR = "#d36c6c"

WINDOW_WIDTH = 480
WINDOW_HEIGHT = 120
FRAME_SPACING = 8
FRAME_WIDTH = WINDOW_WIDTH - FRAME_SPACING * 2
FRAME_HEIGHT = WINDOW_HEIGHT - FRAME_SPACING * 2

BUTTON_SPACING = 4
BUTTON_WIDTH = ((FRAME_WIDTH - 70) / 4) - BUTTON_SPACING
BUTTON_HEIGHT = 30

